
aliases:
  - &restore-node-cache
    keys:
      # bump version for cache invalidation
      - v1-dependencies-{{ checksum "yarn.lock" }}

  - &save-node-cache
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    paths:
      - node_modules/

  - &install-node-dependencies
    |
      yarn install

defaults: &defaults
  working_directory: ~/react-conditional-wrap
  docker:
    - image: circleci/node:8

jobs:
  test-smoke:
    <<: *defaults
    steps:
      - checkout

      - restore_cache: *restore-node-cache
      - run: *install-node-dependencies
      - save_cache: *save-node-cache

      - run: yarn test

workflows:
  version: 2

  build:
    jobs:
      - test-smoke
